create table if not exists public.driver_vehicles (
  id bigint generated by default as identity primary key,
  driver_id bigint not null unique
    references public.drivers (id) on delete cascade,
  make text not null,
  model text not null,
  year text not null,
  colour text not null,
  plate text not null,
  seats integer not null check (seats > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.driver_vehicles (
  driver_id,
  make,
  model,
  year,
  colour,
  plate,
  seats
)
select
  d.id,
  v.value ->> 'make',
  v.value ->> 'model',
  v.value ->> 'year',
  v.value ->> 'colour',
  v.value ->> 'plate',
  (v.value ->> 'seats')::integer
from public.drivers d
cross join lateral (select d.profile_data -> 'vehicle' as value) v
where jsonb_typeof(v.value) = 'object'
  and nullif(v.value ->> 'make', '') is not null
  and nullif(v.value ->> 'model', '') is not null
  and nullif(v.value ->> 'year', '') is not null
  and nullif(v.value ->> 'colour', '') is not null
  and nullif(v.value ->> 'plate', '') is not null
  and coalesce(v.value ->> 'seats', '') ~ '^[0-9]+$'
  and (v.value ->> 'seats')::integer > 0
on conflict (driver_id) do nothing;

create index if not exists driver_vehicles_driver_id_idx
  on public.driver_vehicles using btree (driver_id);

alter table public.driver_vehicles enable row level security;

grant select, insert, update, delete
  on public.driver_vehicles
  to service_role;

grant usage, select
  on sequence public.driver_vehicles_id_seq
  to service_role;
