create table public.driver_ratings (
  id bigint generated by default as identity not null,
  ride_id text not null,
  driver_id bigint not null,
  passenger_clerk_id text not null,
  rating smallint not null,
  comment text null,
  created_at timestamp with time zone not null default now(),
  constraint driver_ratings_pkey primary key (id),
  constraint driver_ratings_ride_id_key unique (ride_id),
  constraint driver_ratings_comment_check check (
    comment is null or char_length(comment) <= 500
  ),
  constraint driver_ratings_rating_check check (
    rating >= 1 and rating <= 5
  )
) tablespace pg_default;

create index if not exists driver_ratings_driver_id_idx
  on public.driver_ratings using btree (driver_id)
  tablespace pg_default;

create index if not exists driver_ratings_passenger_clerk_id_idx
  on public.driver_ratings using btree (passenger_clerk_id)
  tablespace pg_default;
