CREATE TABLE IF NOT EXISTS public.hubs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  address text NOT NULL,
  latitude numeric(10, 8) NOT NULL,
  longitude numeric(11, 8) NOT NULL,
  radius integer NOT NULL DEFAULT 500,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hubs_pkey PRIMARY KEY (id),
  CONSTRAINT hubs_status_check CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]))
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_hubs_status
  ON public.hubs USING btree (status) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_hubs_coordinates
  ON public.hubs USING btree (latitude, longitude) TABLESPACE pg_default;

ALTER TABLE public.hubs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'hubs'
      AND policyname = 'Anyone can view active hubs'
  ) THEN
    CREATE POLICY "Anyone can view active hubs"
      ON public.hubs
      FOR SELECT
      USING (status = 'active');
  END IF;
END
$$;
