create table if not exists public.offer_trip (
  id bigint generated by default as identity not null,

  driver_id bigint not null,

  leaving_from text not null,
  going_to text not null,

  leaving_from_lat double precision null,
  leaving_from_lng double precision null,
  going_to_lat double precision null,
  going_to_lng double precision null,

  departure_date date not null,
  departure_time time without time zone not null,

  repeat_weekly boolean null default false,
  repeat_days text[] null,

  seats_available integer not null default 1,
  seats_booked integer not null default 0,

  price_per_seat numeric(10,2) not null,
  service_fee_percentage numeric(5,2) null default 10.00,
  status text null default 'active',

  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),

  constraint offer_trip_pkey primary key (id),

  constraint offer_trip_driver_id_fkey
    foreign key (driver_id)
    references public.drivers (id)
    on delete cascade,

  constraint offer_trip_seats_available_check
    check (seats_available > 0),

  constraint offer_trip_seats_booked_check
    check (seats_booked >= 0),

  constraint offer_trip_seats_booked_limit_check
    check (seats_booked <= seats_available),

  constraint offer_trip_price_check
    check (price_per_seat >= 0),

  constraint offer_trip_status_check
    check (
      status in (
        'active',
        'full',
        'completed',
        'cancelled'
      )
    )
) tablespace pg_default;

create index if not exists offer_trip_driver_id_idx
  on public.offer_trip (driver_id);

with ranked_active_trips as (
  select
    id,
    row_number() over (
      partition by driver_id
      order by created_at desc, id desc
    ) as row_num
  from public.offer_trip
  where status = 'active'
)
delete from public.offer_trip trip
using ranked_active_trips ranked
where trip.id = ranked.id
  and ranked.row_num > 1;

create unique index if not exists offer_trip_single_active_trip_per_driver_idx
  on public.offer_trip (driver_id)
  where status = 'active';

create index if not exists offer_trip_departure_date_idx
  on public.offer_trip (departure_date);
