create table if not exists public.payouts (
  id bigint generated by default as identity primary key,
  driver_id bigint not null
    references public.drivers (id) on delete cascade,
  amount numeric(12, 2) not null check (amount >= 50),
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'failed')),
  bank_last4 text check (bank_last4 is null or bank_last4 ~ '^[0-9]{4}$'),
  is_mock boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.payouts
  add column if not exists is_mock boolean not null default false;

alter table public.payouts
  alter column bank_last4 drop not null;

create index if not exists payouts_driver_created_at_idx
  on public.payouts using btree (driver_id, created_at desc);

alter table public.payouts enable row level security;

grant select, insert, update, delete
  on public.payouts
  to service_role;

grant usage, select
  on sequence public.payouts_id_seq
  to service_role;
